### PR TITLE
Makes Processes Tab sortable

### PR DESCRIPTION
**Pull request by aabbi**
I've found this useful to see which processes have say, the most GPU utilization. sort of like how top/htop work with sorting.

### CODE REVIEW

**Comment by congard** [comment]
Hi, thank you for contributing, but I noticed that sorting breaks after the data update. I will check your code later and try to fix it

**Comment by aabbi** [comment]
Oh I see - seems to be working for me as I would expect
sorting
Maybe our libs have different version ? Let me know if youd like to know info about any specific lib (although they should mostly be the ones as specified in the dependencies in the readme)

**Comment by congard** [comment]
Hi, my qt version:
`extra/qt5-base 5.15.0-4 (qt qt5) [installed]`

**Comment by aabbi** [comment]
I was on qt 5.11 and was working fine there. 
I upgraded to 5.14.2 (cant do 5.15 with my OS yet) and looks like sorting breaks on data update. Will try and see if I can fix it

**Comment by congard** [comment]
@aabbi Hi, can you test the latest [`master`](https://github.com/congard/nvidia-system-monitor-qt), please? I just need to make sure everything's okay

**Comment by aabbi** [comment]
@congard just did - sorting works and can see the changes you made to the graphs. thanks - looks good!

**Pull request closed without merging**
